"""
Data schemas for the LOB environment using Pydantic.

This module defines the core data structures used throughout the simulation,
enforcing strict typing for Groq JSON outputs and accurate Order Book physics.
"""

from typing import List, Tuple, Literal
from pydantic import BaseModel, Field

class Order(BaseModel):
    """
    Represents a single order in the limit order book.
    
    Implements self-aware Price-Time Priority for sorting:
    - BIDS: Higher prices come first.
    - ASKS: Lower prices come first.
    - TIES: Earlier timestamps come first.
    """
    order_id: str = Field(..., description="Unique order identifier")
    side: Literal["BUY", "SELL"] = Field(..., description="Order side: BUY or SELL")
    price: float = Field(..., description="Order limit price", gt=0)
    quantity: int = Field(..., description="Order quantity in shares", gt=0)
    timestamp: float = Field(..., description="Order submission timestamp (seconds since epoch)")
    agent_id: str = Field(..., description="ID of agent that placed this order")

    def __lt__(self, other: 'Order') -> bool:
        """
        Price-Time Priority sorting logic.
        Allows standard Python sorting (e.g., sort(), heapq) to automatically
        create the correct order book hierarchy without negative price hacks.
        """
        # 1. Price Priority
        if self.price != other.price:
            if self.side == "BUY":
                return self.price > other.price  # Higher bids win
            else:
                return self.price < other.price  # Lower asks win
                
        # 2. Time Priority (If prices match, older orders win)
        return self.timestamp < other.timestamp


class Trade(BaseModel):
    """
    Represents an executed trade between a buyer and a seller.
    Immutable record generated by the Matching Engine.
    """
    trade_id: str = Field(..., description="Unique trade identifier")
    buyer_id: str = Field(..., description="ID of buyer agent")
    seller_id: str = Field(..., description="ID of seller agent")
    price: float = Field(..., description="Execution price", gt=0)
    quantity: int = Field(..., description="Executed quantity in shares", gt=0)
    timestamp: float = Field(..., description="Execution timestamp")


class AgentState(BaseModel):
    """
    Observation state provided to the LLM agent at each step.
    Strictly formatted to minimize token count while maximizing L2 context.
    """
    time_remaining: int = Field(..., description="Steps remaining until episode termination")
    inventory_remaining: int = Field(..., description="Shares remaining to execute")
    mid_price: float = Field(..., description="Current mid-price: (best_bid + best_ask) / 2")
    bids: List[Tuple[float, int]] = Field(
        ..., 
        description="Top 3 bid levels: [(price, quantity), ...]"
    )
    asks: List[Tuple[float, int]] = Field(
        ..., 
        description="Top 3 ask levels: [(price, quantity), ...]"
    )
    
    # --- HYBRID NLP STATE FIELDS ---
    market_shape: str = Field(
        default="BALANCED",
        description="Semantic NLP description of order book imbalance and liquidity walls."
    )
    compliance_mandate: str = Field(
        default="Standard execution.",
        description="Text-based institutional rules you MUST follow this episode."
    )


class AgentAction(BaseModel):
    """
    Action taken by LLM agent for execution.
    Uses Literal types to enforce strict LLM JSON compliance.
    """
    side: Literal["BUY", "SELL"] = Field(
        ..., 
        description="Direction of the execution block"
    )
    shares_to_execute: int = Field(
        ..., 
        description="Number of shares to execute (must be >= 0)",
        ge=0
    )
    execution_style: Literal["AGGRESSIVE", "PASSIVE"] = Field(
        ..., 
        description="'AGGRESSIVE' (crosses spread) or 'PASSIVE' (joins best bid/ask)"
    )


class StepReward(BaseModel):
    """Reward structure for a single step in the LOB environment."""
    total_reward: float = Field(..., description="Slippage penalty (negative value) or 0")
    done: bool = Field(default=False, description="Episode termination flag")